name: movies_from_api
description: Get movie list with filtering by user parameters

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  cupertino_icons: ^0.1.3
  built_value: ^7.1.0
  built_collection: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: '>=1.0.0 <2.0.0'
  built_value_generator: ^7.1.0

flutter:
  uses-material-design: true
